### PR TITLE
Add avaron

### PR DESCRIPTION
**Pull request by bokuweb**
Add  `avaron` to `Pacakges`.

### CODE REVIEW

**Comment by novemberborn** [comment]
Speaking for myself, I'm not sure we'd want to be promoting forks of AVA.

Would love to work together to see if we can make AVA itself run with Electron though.

**Comment by bokuweb** [comment]
@novemberborn Noted with thanks. I close this PR.

**Comment by sindresorhus** [comment]
@bokuweb Can you open an issue on the main AVA issue tracker about adding hooks so you can do Electron support without having to fork AVA?

**Comment by bokuweb** [comment]
@sindresorhus Thanks. I'll organize it and then open issue.

**Pull request closed without merging**
